### ISSUE TITLE
Package is unregistered

### ISSUE THREAD

**Issue by hersle** [komatsu5147/MatterPower.jl#1]
Hi there! 😃 

Is there any chance you would like to register this nice little package? I would love to use it as a lightweight dependency in [SymBoltz.jl](https://github.com/hersle/SymBoltz.jl) with a convenience interface to [compute some quantities derived from the power spectrum](https://hersle.github.io/SymBoltz.jl/dev/spectra/).

This is cumbersome when it is unregistered. If so, I will make sure to credit your package in mine.

All the best! - Herman

**Comment by komatsu5147** [comment]
@JuliaRegistrator register

**Comment by komatsu5147** [comment]
@JuliaRegistrator register

**Comment by hersle** [comment]
Thanks! I [added](https://github.com/hersle/SymBoltz.jl/commit/59794f892a70ea6313bf42d82c294957eddad7d5) it now.

**Comment by komatsu5147** [comment]
@JuliaRegistrator register

**Comment by komatsu5147** [comment]
@JuliaRegistrator register
